### ISSUE TITLE
Cannot read property 'has_cfp' of undefined

### ISSUE THREAD

**Issue by TejasQ** [asciidisco/cfp-magick#7]
* **I'm submitting a bug report**

* **Do you want to request a *feature* or report a *bug*?**
Report a bug

* **What is the current behavior?**
![lel](https://user-images.githubusercontent.com/9947422/35325835-2e162caa-00f5-11e8-90a3-0f70161b99b6.gif)

```
An error occured:
TypeError: Cannot read property 'has_cfp' of undefined
    at conferences.filter.conf (/Users/tejaskumar/.config/yarn/global/node_modules/cfp-magick/src/filter_by_cfp.js:2:68)
    at Array.filter (<anonymous>)
    at module.exports.conferences (/Users/tejaskumar/.config/yarn/global/node_modules/cfp-magick/src/filter_by_cfp.js:2:45)
    at module.exports.conferenceData (/Users/tejaskumar/.config/yarn/global/node_modules/cfp-magick/src/reducer.js:6:36)
    at module.exports (/Users/tejaskumar/.config/yarn/global/node_modules/cfp-magick/index.js:8:25)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 
Erm, just running the command should do it.

* **What is the expected behavior?**
![GIF from README](https://raw.githubusercontent.com/asciidisco/cfp-magick/master/demo.gif)

* **What is the motivation / use case for changing the behavior?**
So that it works 😄 

* **Please tell us about your environment:**
Mac OS X 10.13.2, using iTerm with zshell, node `v8.6.0` and npm `v5.6.0`

**Comment by asciidisco** [comment]
Thanks for the report, it was a problem in the data source.
Should work now.

**Comment by TejasQ** [comment]
Thank you for the quick fix, @asciidisco!
